- hosts: nginx
  become: yes
  become_user: root
  gather_facts: false
  vars:
   - ansible_ssh_user: ubuntu

  tasks:
   - name: hello.php copy
     copy: src=conv-json.php dest=/var/www/html/conv-json.php

